version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    ignore:
      - dependency-name: 'chalk'
        versions: ['5.x']
      - dependency-name: 'storybook'
      - dependency-name: '@storybook/*'
      - dependency-name: 'react'
      - dependency-name: 'react-dom'
      - dependency-name: 'eslint'
      - dependency-name: '@headlessui/react'
