name: Cypress-E2E Visitor Side
on:
  pull_request: ~
  push:
    branches:
      - main
jobs:
  cypress-e2e-visitor-side:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/prepare
      - run: mv .env.sample .env
      - run: docker-compose up -d
      - uses: cypress-io/github-action@v4
        with:
          spec: cypress/e2e/visitor_basic.cy.js
          start: yarn server:start, yarn start
          wait-on: 'http://localhost:3000'
      - uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
      # Test run video was always captured, so this action uses "always()" condition
#      - uses: actions/upload-artifact@v2
#        if: always()
#        with:
#          name: cypress-videos
#          path: cypress/videos
